#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rack
Version  : 1.6.2
Release  : 13
URL      : https://rubygems.org/downloads/rack-1.6.2.gem
Source0  : https://rubygems.org/downloads/rack-1.6.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-rack-bin
BuildRequires : ruby
BuildRequires : rubygem-bacon
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
= Rack, a modular Ruby webserver interface {<img src="https://secure.travis-ci.org/rack/rack.svg" alt="Build Status" />}[http://travis-ci.org/rack/rack] {<img src="https://gemnasium.com/rack/rack.svg" alt="Dependency Status" />}[https://gemnasium.com/rack/rack]

%package bin
Summary: bin components for the rubygem-rack package.
Group: Binaries

%description bin
bin components for the rubygem-rack package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rack-1.6.2
gem spec %{SOURCE0} -l --ruby > rubygem-rack.gemspec

%build
gem build rubygem-rack.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rack-1.6.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/rack-1.6.1 && bacon -Ilib --automatic --quiet && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rack-1.6.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/KNOWN-ISSUES
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/SPEC
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/bin/rackup
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/contrib/rack.png
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/contrib/rack.svg
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/contrib/rack_logo.svg
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/contrib/rdoc.css
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/example/lobster.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/example/protectedlobster.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/example/protectedlobster.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/abstract/handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/abstract/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/digest/md5.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/digest/nonce.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/digest/params.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/auth/digest/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/backports/uri/common_18.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/backports/uri/common_192.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/backports/uri/common_193.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/body_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/cascade.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/chunked.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/commonlogger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/conditionalget.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/config.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/content_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/content_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/deflater.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/etag.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/cgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/evented_mongrel.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/fastcgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/lsws.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/mongrel.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/scgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/swiftiplied_mongrel.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/thin.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/handler/webrick.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/head.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/lint.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/lobster.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/lock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/methodoverride.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/mime.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/multipart.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/multipart/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/multipart/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/multipart/uploaded_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/nulllogger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/recursive.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/reloader.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/rewindable_input.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/sendfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/server.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/session/abstract/id.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/session/cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/session/memcache.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/session/pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/showexceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/showstatus.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/static.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/tempfile_reaper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/urlmap.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/lib/rack/utils/okjson.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/rack.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/builder/anything.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/builder/comment.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/builder/end.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/builder/line.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/builder/options.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/folder/test.js
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/fonts/font.eot
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/images/image.png
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/index.html
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/javascripts/app.js
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/assets/stylesheets/app.css
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/lighttpd.conf
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/rackup_stub.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/sample_rackup.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/test
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/test+directory/test+file
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/test.fcgi
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/cgi/test.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/gemloader.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/bad_robots
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/binary
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/content_type_and_no_filename
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/empty
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/fail_16384_nofile
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/file1.txt
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_and_modification_param
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_and_no_name
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_escaped_quotes
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_escaped_quotes_and_modification_param
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_percent_escaped_quotes
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_unescaped_percentages
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_unescaped_percentages2
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_unescaped_percentages3
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/filename_with_unescaped_quotes
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/ie
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/invalid_character
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/mixed_files
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/nested
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/none
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/semicolon
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/text
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/multipart/webkit
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/rackup/config.ru
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/registering_handler/rack/handler/registering_myself.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_auth_basic.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_auth_digest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_body_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_cascade.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_cgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_chunked.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_commonlogger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_conditionalget.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_config.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_content_length.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_content_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_deflater.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_directory.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_etag.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_fastcgi.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_file.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_handler.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_head.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_lint.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_lobster.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_lock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_methodoverride.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_mime.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_mock.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_mongrel.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_multipart.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_nulllogger.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_recursive.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_request.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_rewindable_input.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_runtime.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_sendfile.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_server.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_session_abstract_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_session_cookie.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_session_memcache.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_session_pool.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_showexceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_showstatus.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_static.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_tempfile_reaper.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_thin.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_urlmap.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/spec_webrick.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/static/another/index.html
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/static/index.html
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/testrequest.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/unregistered_handler/rack/handler/unregistered.rb
/usr/lib64/ruby/gems/2.3.0/gems/rack-1.6.2/test/unregistered_handler/rack/handler/unregistered_long_one.rb
/usr/lib64/ruby/gems/2.3.0/specifications/rack-1.6.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/rackup
